### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by rpd** [monkeyinmysoup/BitChess#6]
Hi
Today I found Bitchess and tried Make (Win8PC) but failed with;
C:\RPD_Computing_Programming\RPD_Chess_programming\BitChess C cli engine\BitChes
s-master>make
MAKE Version 5.4  Copyright (c) 1987, 2010 Embarcadero Technologies, Inc.
Error makefile 33: Command syntax error
Error makefile 38: Command syntax error
Error makefile 43: Command syntax error
Error makefile 48: Command syntax error
*** 4 errors during make ***

Any ideas why I'm getting these errors? Grateful for any help..thanks :-)

**Comment by monkeyinmysoup** [comment]
Hi!
My guess is that the version of Make you're using does not support the '  +=  ' command that appears on those lines. I myself use [GNU Make 3.81][make] on Windows 8.

Perhaps it helps to substitute the relevant lines with this construction:

    CFLAGS = $(CFLAGS) -finput-charset=UTF-8

[make]: http://gnuwin32.sourceforge.net/packages/make.htm#download

**Comment by monkeyinmysoup** [comment]
I'll close this issue since the project assumes the use of the gcc build tools.

**Comment by rpd** [comment]
Thanks for your helpful reply (sorry for this delayed acknowledgment). I plan to follow up this and fix my make implentation issue sometime.. :-)
